### ISSUE TITLE
Basic communication inference

### ISSUE THREAD

**Issue by dplyukhin** [Blesting/choral#3]
Given a Choral file with insufficient communications, generate a new version of the file with communications inserted.

# Week 1

- [x] After `RelaxedTyper`, run `PrettyPrinterVisitor` to convert each Choral AST into a string and write that string into the `target/` directory.
  - [x] If you give PrettyPrinterVisitor a well-typed and projectable Choral AST, does it print out a well-typed and projectable Choral file? If not, what are the key issues? You'll have to create your own version of the visitor that actually does compile.
- [x] Create a new class in the `amend` package that will modify your AST, adding communications. In your first commit, the class shouldn't do anything. What are the next steps?

**Comment by Blesting** [comment]
# Week 2

Filtering the channels:
- [ ] Filter channels based on roles.
- [ ] Maybe also filter channels based on type parameters.

Inferring communications:
- [ ] Figure out how to create a new expression.
- [ ] Insert a new expression into the AST.

**Comment by dplyukhin** [comment]
@Blesting Last few tasks before the PR is ready to merge!

- [x] Add a `CommunicationInferenceError` to the `choral/exceptions` directory. When `RelaxedTyper` or `BasicInference` encounter a problem and would normally return null, throw an error instead with an informative error message. (Feel free to add multiple kinds exceptions in the `choral/exceptions` directory if you think it would help!)
- [x] Add a flag to disable the "most specific overload" feature. This flag will be useful when somebody tries to design a "location inference" feature (maybe that person will be you, if you want to go down that road!).
- [x] Merge the PR, close this issue, and enjoy your holiday ☑️

We'll resume work on January 6! The plan for next semester is some concurrent composition of: (1) begin writing the thesis, (2) present a short demo of your work for early feedback, (3) develop an evaluation, and (4) develop some more interesting optimizations.
